# Generated by Django 3.1.7 on 2021-03-14 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('all_or_any', models.BooleanField()),
                ('choice', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TaskSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='workflow_app.tasktemplate')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='workflow_app.tasktemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.CharField(max_length=200)),
                ('deadline', models.DateTimeField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_app.process')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow_app.tasktemplate')),
            ],
        ),
    ]
