# Generated by Django 3.1.7 on 2021-03-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_app', '0003_auto_20210314_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtemplate',
            name='tasks',
            field=models.ManyToManyField(to='workflow_app.TaskTemplate'),
        ),
    ]
